name: Run Azure Login with OpenID Connect

on: workflow_call

permissions:
      id-token: write
      contents: read
      
jobs: 
  login-to-azure:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
    - name: 'Az CLI login'
      uses: azure/login@v2
      with:
          auth-type: SERVICE_PRINCIPAL # IDENTITY
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          # client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}