name: GitOps Pipeline
on:
  push:
    branches:
      - master
jobs:
  deploy-to-azure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Set ip Terraform
        uses: ./.github/workflows/log-to-azure.yml

      - name: Current dir
        run: echo "CurrDir $(pwd)"

      - name: Init Terraform
        run: terraform init
        working-directory: ./terraform

      - name: Validate Terraform
        run: terraform validate
        working-directory: ./terraform

      - name: Plan Terraform
        run: terraform plan
        working-directory: ./terraform

