name: Run Azure Login with OpenID Connect
on: 
  workflow_dispatch:

permissions:
      id-token: write
      contents: read
      
jobs: 
  login-to-azure:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
    - name: 'Az CLI login'
      uses: azure/login@v2
      with:
          auth-type: SERVICE_PRINCIPAL # IDENTITY
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          # client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
  deploy-terraform-resources:
    runs-on: ubuntu-latest
    environment: DEV        
    steps:
    - name: 'Checkout GitHub Actions'
      uses: actions/checkout@v4

    - name: 'Run Azure CLI commands'
      run: |
          az account show
          az group list
          pwd

    # - name: 'Set up Terraform'
    #   uses: hashicorp/setup-terraform@v3

    # - name: 'Terraform Init'
    #   run: terraform init
    #   working-directory: ./terraform/setup-backend-resources

    # - name: 'Terraform Plan'
    #   run: terraform plan
    #   working-directory: ./terraform/setup-backend-resources
    #   env:
    #     ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
    #     # ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
    #     ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    #     ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        
    # - name: 'Terraform Apply'
    #   # if: github.ref == 'refs/heads/establish-login-to-azure'
    #   run: terraform apply -auto-approve
    #   working-directory: ./terraform/setup-backend-resources
      
