name: 'Terraform Plan and Apply'

on:
  workflow_dispatch:

jobs:
  auth-to-az:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
    - name: 'Az CLI login'
      uses: azure/login@v2
      
  
    - name: 'Run Azure CLI commands'
      run: |
          az account show
          az group list
          pwd
  # terraform:
